SSD300:
  ratios: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
  scales: [0.1, 0.2, 0.375, 0.55, 0.725, 0.9, 1.075]
  fm_sizes: [38, 19, 10, 5, 3, 1]
  image_size: 300

SSD300_text:
  aspect_ratios: [[1, 3, 5], [1, 3, 5], [1, 6, 8], [1, 4, 7], [1, 6, 8], [1, 5, 7]]
  scales: [[.1, .2], [.2, .3], [.2, .4], [.3, .4], [.3, .5], [.4, .6]]
  feat_map_size: [38, 19, 10, 5, 3, 1]
  image_size: 300

SSD512:
  aspect_ratios: [[2], [2, 3], [2, 3], [2, 3], [2], [2], [2]]
  scales: [0.07, 0.15, 0.3, 0.45, 0.6, 0.75, 0.9, 1.05]
  feat_map_size: [64, 32, 16, 8, 6, 4, 1]
  image_size: 512
